spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: none
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath*:/db/changelog/db.changelog-master.xml

logging:
  level:
    org:
      hibernate:
        type: trace


ml:
  pevgen:
    example:
      springrestsimple:
        simpleProperty: valueFromConfig